// 빌드 시 ../src/content/*.md 의 도움말 14문서를 src/help-content.ts 에
// string literal 로 inline 합니다. search_help 도구가 백엔드 호출 없이
// 자체 매칭 — 도움말 갱신 시 패키지 새 버전 publish 가 갱신 전파 채널 (D8).
//
// content/ 의 마크다운은 main monorepo (open-notion) 의 packages/web/src/
// help/content 와 sync 가 필요합니다. 도움말 갱신 절차:
//   1. main monorepo 에서 도움말 .md 갱신
//   2. `cp packages/web/src/help/content/*.md packages/mcp/src/content/`
//   3. mcp version bump + `npm publish`

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const HELP_DIR = resolve(__dirname, "../src/content");
const OUT_FILE = resolve(__dirname, "../src/help-content.ts");

function main(): void {
  const files = readdirSync(HELP_DIR).filter((f) => f.endsWith(".md"));
  files.sort();

  const entries: Record<string, string> = {};
  for (const f of files) {
    const slug = f.replace(/\.md$/, "");
    entries[slug] = readFileSync(resolve(HELP_DIR, f), "utf-8");
  }

  const code =
    "// Auto-generated by scripts/embed-help.ts. Do not edit by hand.\n" +
    "// Run `pnpm build` (or `pnpm exec tsx scripts/embed-help.ts`) to refresh.\n" +
    "\n" +
    `export const HELP_CONTENT: Record<string, string> = ${JSON.stringify(
      entries,
      null,
      2,
    )};\n`;

  writeFileSync(OUT_FILE, code);
  console.log(
    `[embed-help] wrote ${files.length} articles → src/help-content.ts`,
  );
}

main();
